version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081" # Nexus UI
      # We will enable these widely known ports for Docker later
      - "8082:8082" # Docker Hosted
      # - "8083:8083" # Docker Group
    volumes:
      - nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2G
    restart: unless-stopped

volumes:
  nexus-data:
